// Copyright © 2026 Luther Systems, Ltd. All right reserved.

package libhandlebars

import (
	"encoding/json"
	"reflect"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestRawMessageOwnMethodLineDirective: a type declaring its own
// MarshalJSON over an embedded RawMessage encodes with its method, however
// the method is attributed (here to "<autogenerated>", as compiler
// wrappers are): the walk does not fail on the RawMessage's bytes.
func TestRawMessageOwnMethodLineDirective(t *testing.T) {
	v := jsLineOwn{json.RawMessage("x")}
	want, err := json.Marshal(v)
	require.NoError(t, err)
	require.JSONEq(t, `{"x":1}`, string(want))
	require.NoError(t, goJSONCost(&goBudget{max: 1 << 40}, reflect.ValueOf(v), 0))
	tpl, err := Parse(`{{x}}`)
	require.NoError(t, err)
	out, err := RenderWith(tpl, v, WithJSONContext())
	require.NoError(t, err)
	require.Equal(t, "1", out)
}

type jsLineOwn struct{ json.RawMessage }

// The directive must stay last in this file: it renames what follows.
//
//line <autogenerated>:1
func (jsLineOwn) MarshalJSON() ([]byte, error) { return []byte(`{"x":1}`), nil }
