// Copyright © 2026 Luther Systems, Ltd. All right reserved.

package libhandlebars_test

// sparse100 has 100 omitempty fields (generated): encoding/json visits
// each, empty or not.
type sparse100 struct {
	F0  int `json:",omitempty"`
	F1  int `json:",omitempty"`
	F2  int `json:",omitempty"`
	F3  int `json:",omitempty"`
	F4  int `json:",omitempty"`
	F5  int `json:",omitempty"`
	F6  int `json:",omitempty"`
	F7  int `json:",omitempty"`
	F8  int `json:",omitempty"`
	F9  int `json:",omitempty"`
	F10 int `json:",omitempty"`
	F11 int `json:",omitempty"`
	F12 int `json:",omitempty"`
	F13 int `json:",omitempty"`
	F14 int `json:",omitempty"`
	F15 int `json:",omitempty"`
	F16 int `json:",omitempty"`
	F17 int `json:",omitempty"`
	F18 int `json:",omitempty"`
	F19 int `json:",omitempty"`
	F20 int `json:",omitempty"`
	F21 int `json:",omitempty"`
	F22 int `json:",omitempty"`
	F23 int `json:",omitempty"`
	F24 int `json:",omitempty"`
	F25 int `json:",omitempty"`
	F26 int `json:",omitempty"`
	F27 int `json:",omitempty"`
	F28 int `json:",omitempty"`
	F29 int `json:",omitempty"`
	F30 int `json:",omitempty"`
	F31 int `json:",omitempty"`
	F32 int `json:",omitempty"`
	F33 int `json:",omitempty"`
	F34 int `json:",omitempty"`
	F35 int `json:",omitempty"`
	F36 int `json:",omitempty"`
	F37 int `json:",omitempty"`
	F38 int `json:",omitempty"`
	F39 int `json:",omitempty"`
	F40 int `json:",omitempty"`
	F41 int `json:",omitempty"`
	F42 int `json:",omitempty"`
	F43 int `json:",omitempty"`
	F44 int `json:",omitempty"`
	F45 int `json:",omitempty"`
	F46 int `json:",omitempty"`
	F47 int `json:",omitempty"`
	F48 int `json:",omitempty"`
	F49 int `json:",omitempty"`
	F50 int `json:",omitempty"`
	F51 int `json:",omitempty"`
	F52 int `json:",omitempty"`
	F53 int `json:",omitempty"`
	F54 int `json:",omitempty"`
	F55 int `json:",omitempty"`
	F56 int `json:",omitempty"`
	F57 int `json:",omitempty"`
	F58 int `json:",omitempty"`
	F59 int `json:",omitempty"`
	F60 int `json:",omitempty"`
	F61 int `json:",omitempty"`
	F62 int `json:",omitempty"`
	F63 int `json:",omitempty"`
	F64 int `json:",omitempty"`
	F65 int `json:",omitempty"`
	F66 int `json:",omitempty"`
	F67 int `json:",omitempty"`
	F68 int `json:",omitempty"`
	F69 int `json:",omitempty"`
	F70 int `json:",omitempty"`
	F71 int `json:",omitempty"`
	F72 int `json:",omitempty"`
	F73 int `json:",omitempty"`
	F74 int `json:",omitempty"`
	F75 int `json:",omitempty"`
	F76 int `json:",omitempty"`
	F77 int `json:",omitempty"`
	F78 int `json:",omitempty"`
	F79 int `json:",omitempty"`
	F80 int `json:",omitempty"`
	F81 int `json:",omitempty"`
	F82 int `json:",omitempty"`
	F83 int `json:",omitempty"`
	F84 int `json:",omitempty"`
	F85 int `json:",omitempty"`
	F86 int `json:",omitempty"`
	F87 int `json:",omitempty"`
	F88 int `json:",omitempty"`
	F89 int `json:",omitempty"`
	F90 int `json:",omitempty"`
	F91 int `json:",omitempty"`
	F92 int `json:",omitempty"`
	F93 int `json:",omitempty"`
	F94 int `json:",omitempty"`
	F95 int `json:",omitempty"`
	F96 int `json:",omitempty"`
	F97 int `json:",omitempty"`
	F98 int `json:",omitempty"`
	F99 int `json:",omitempty"`
}
